name:                xolsh
version:             0.1.0.0
github:              "0rphee/xolsh"
license:             BSD3
author:              "0rphee"
maintainer:          "0rph3e@proton.me"
copyright:           "2023 0rphee"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/0rphee/xolsh#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- RecordWildCards

language: GHC2021

executables:
  xolsh-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - optparse-applicative

tests:
  xolsh-test:
    main:                Spec.hs
    source-dirs:         
    - test
    - app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
